/**
 * Firemix - Bundle.yaml generator
 * Generates the .apphosting/bundle.yaml file for Firebase App Hosting
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import type { BundleYaml, FiremixConfig } from "./types.js";
import {
  assertNoDevDependenciesInstalled,
  checkFileSize,
  safeParsePackageJson,
  sanitizeBuildDir,
  validateRunConfig,
} from "./validation.js";

// ESM equivalent of __dirname
const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Get the adapter version from package.json
 */
function getAdapterVersion(): string {
  try {
    const pkgPath = join(__dirname, "..", "package.json");
    checkFileSize(pkgPath);
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version?: string };
    return pkg.version || "0.1.0";
  } catch {
    return "0.1.0";
  }
}

/**
 * Detect Remix version from the project
 */
function getRemixVersion(projectRoot: string): string | undefined {
  try {
    const pkgPath = join(projectRoot, "package.json");
    const pkg = safeParsePackageJson(pkgPath);

    const version =
      pkg.dependencies?.["@remix-run/node"] ||
      pkg.dependencies?.["@remix-run/react"] ||
      pkg.devDependencies?.["@remix-run/dev"];

    return version;
  } catch (error) {
    console.warn(`Failed to read Remix version: ${error instanceof Error ? error.message : "Unknown error"}`);
    return undefined;
  }
}

/**
 * Generate the bundle.yaml content
 */
export function generateBundle(projectRoot: string, config: FiremixConfig = {}): BundleYaml {
  // Validate and sanitize buildDir
  const buildDir = sanitizeBuildDir(config.buildDir || "build");

  // Validate runConfig numeric values
  const runConfig = validateRunConfig(config.runConfig || {});

  // Ensure we are not packaging development dependencies unless explicitly allowed
  assertNoDevDependenciesInstalled(projectRoot, config.allowDevDependencies);

  return {
    version: "v1",
    runConfig: {
      runCommand: `node ${buildDir}/server/index.js`,
      concurrency: runConfig.concurrency,
      cpu: runConfig.cpu,
      memoryMiB: runConfig.memoryMiB,
      minInstances: runConfig.minInstances,
      maxInstances: runConfig.maxInstances,
    },
    outputFiles: {
      serverApp: {
        include: [buildDir, "node_modules", "package.json"],
      },
      staticAssets: {
        include: [`${buildDir}/client`],
      },
    },
    metadata: {
      adapterPackageName: "firemix",
      adapterVersion: getAdapterVersion(),
      framework: "remix",
      frameworkVersion: getRemixVersion(projectRoot),
    },
  };
}

/**
 * Escape a string for safe YAML output
 */
function escapeYamlValue(value: string): string {
  // If the value contains special characters, quote it
  if (/[:#\[\]{},"'|>&*!?\\]/.test(value) || value.includes("\n")) {
    // Escape backslashes and double quotes, then wrap in double quotes
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Serialize bundle to YAML string
 */
export function serializeBundle(bundle: BundleYaml): string {
  const lines: string[] = [
    "# Generated by Firemix - Firebase App Hosting adapter for Remix",
    "# https://github.com/yhakami/firemix",
    "",
    `version: ${bundle.version}`,
    "",
    "runConfig:",
    `  runCommand: ${escapeYamlValue(bundle.runConfig.runCommand)}`,
    `  concurrency: ${bundle.runConfig.concurrency}`,
    `  cpu: ${bundle.runConfig.cpu}`,
    `  memoryMiB: ${bundle.runConfig.memoryMiB}`,
    `  minInstances: ${bundle.runConfig.minInstances}`,
    `  maxInstances: ${bundle.runConfig.maxInstances}`,
    "",
    "outputFiles:",
    "  serverApp:",
    "    include:",
    ...bundle.outputFiles.serverApp.include.map((p) => `      - ${escapeYamlValue(p)}`),
  ];

  if (bundle.outputFiles.staticAssets) {
    lines.push("  staticAssets:", "    include:");
    lines.push(...bundle.outputFiles.staticAssets.include.map((p) => `      - ${escapeYamlValue(p)}`));
  }

  lines.push(
    "",
    "metadata:",
    `  adapterPackageName: ${escapeYamlValue(bundle.metadata.adapterPackageName)}`,
    `  adapterVersion: ${escapeYamlValue(bundle.metadata.adapterVersion)}`,
    `  framework: ${escapeYamlValue(bundle.metadata.framework)}`
  );

  if (bundle.metadata.frameworkVersion) {
    lines.push(`  frameworkVersion: ${escapeYamlValue(bundle.metadata.frameworkVersion)}`);
  }

  return lines.join("\n") + "\n";
}
