/**
 * Firemix - Bundle.yaml generator
 * Generates the .apphosting/bundle.yaml file for Firebase App Hosting
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { BundleYaml, FiremixConfig, RunConfig } from "./types.js";

const DEFAULT_RUN_CONFIG: Required<RunConfig> = {
  minInstances: 0,
  maxInstances: 10,
  concurrency: 80,
  cpu: 1,
  memoryMiB: 512,
};

/**
 * Get the adapter version from package.json
 */
function getAdapterVersion(): string {
  try {
    const pkgPath = join(import.meta.dirname, "..", "package.json");
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
    return pkg.version || "0.1.0";
  } catch {
    return "0.1.0";
  }
}

/**
 * Detect Remix version from the project
 */
function getRemixVersion(projectRoot: string): string | undefined {
  try {
    const pkgPath = join(projectRoot, "package.json");
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
    return (
      pkg.dependencies?.["@remix-run/node"] ||
      pkg.dependencies?.["@remix-run/react"] ||
      pkg.devDependencies?.["@remix-run/dev"]
    );
  } catch {
    return undefined;
  }
}

/**
 * Generate the bundle.yaml content
 */
export function generateBundle(
  projectRoot: string,
  config: FiremixConfig = {}
): BundleYaml {
  const buildDir = config.buildDir || "build";
  const runConfig = { ...DEFAULT_RUN_CONFIG, ...config.runConfig };

  return {
    version: "v1",
    runConfig: {
      runCommand: `node ${buildDir}/server/index.js`,
      concurrency: runConfig.concurrency,
      cpu: runConfig.cpu,
      memoryMiB: runConfig.memoryMiB,
      minInstances: runConfig.minInstances,
      maxInstances: runConfig.maxInstances,
    },
    outputFiles: {
      serverApp: {
        include: [buildDir, "node_modules", "package.json"],
      },
      staticAssets: {
        include: [`${buildDir}/client`],
      },
    },
    metadata: {
      adapterPackageName: "firemix",
      adapterVersion: getAdapterVersion(),
      framework: "remix",
      frameworkVersion: getRemixVersion(projectRoot),
    },
  };
}

/**
 * Serialize bundle to YAML string
 */
export function serializeBundle(bundle: BundleYaml): string {
  const lines: string[] = [
    "# Generated by Firemix - Firebase App Hosting adapter for Remix",
    "# https://github.com/yhakami/firemix",
    "",
    `version: ${bundle.version}`,
    "",
    "runConfig:",
    `  runCommand: ${bundle.runConfig.runCommand}`,
    `  concurrency: ${bundle.runConfig.concurrency}`,
    `  cpu: ${bundle.runConfig.cpu}`,
    `  memoryMiB: ${bundle.runConfig.memoryMiB}`,
    `  minInstances: ${bundle.runConfig.minInstances}`,
    `  maxInstances: ${bundle.runConfig.maxInstances}`,
    "",
    "outputFiles:",
    "  serverApp:",
    "    include:",
    ...bundle.outputFiles.serverApp.include.map((p) => `      - ${p}`),
  ];

  if (bundle.outputFiles.staticAssets) {
    lines.push("  staticAssets:", "    include:");
    lines.push(
      ...bundle.outputFiles.staticAssets.include.map((p) => `      - ${p}`)
    );
  }

  lines.push(
    "",
    "metadata:",
    `  adapterPackageName: ${bundle.metadata.adapterPackageName}`,
    `  adapterVersion: ${bundle.metadata.adapterVersion}`,
    `  framework: ${bundle.metadata.framework}`
  );

  if (bundle.metadata.frameworkVersion) {
    lines.push(`  frameworkVersion: "${bundle.metadata.frameworkVersion}"`);
  }

  return lines.join("\n") + "\n";
}
